This notebook is the preprocessing and general format of the architecture for the deep neural network. The midterm-train notebook is for executing the training.

In [0]:
#!/usr/bin/python3

# Packages

In [0]:
#installing tensorflow
!pip install tensorflow

In [0]:
!pip install keras

In [0]:
!pip install numpy

# Loading From Link and Saving to Google Drive

In [0]:
!wget https://pubdata.endgame.com/ember/ember_dataset_2017_2.tar.bz2

--2020-04-03 18:58:32--  https://pubdata.endgame.com/ember/ember_dataset_2017_2.tar.bz2
Resolving pubdata.endgame.com (pubdata.endgame.com)... 64.250.189.21
Connecting to pubdata.endgame.com (pubdata.endgame.com)|64.250.189.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1751237573 (1.6G) [application/octet-stream]
Saving to: ‘ember_dataset_2017_2.tar.bz2’

ember_dataset_2017_ 100%[===================>]   1.63G  14.2MB/s    in 2m 39s  

2020-04-03 19:01:13 (10.5 MB/s) - ‘ember_dataset_2017_2.tar.bz2’ saved [1751237573/1751237573]



In [0]:
!bzip2 -d ember_dataset_2017_2.tar.bz2

In [0]:
!tar -xvf ember_dataset_2017_2.tar

ember_2017_2/
ember_2017_2/train_features_1.jsonl
ember_2017_2/train_features_0.jsonl
ember_2017_2/train_features_3.jsonl
ember_2017_2/test_features.jsonl
ember_2017_2/train_features_5.jsonl
ember_2017_2/train_features_4.jsonl
ember_2017_2/train_features_2.jsonl


In [0]:
!rm ember_dataset_2017_2.tar

rm: cannot remove 'ember_dataset_2017_2.tar': No such file or directory


In [0]:
!wget https://github.com/endgameinc/ember/archive/master.zip
!unzip master.zip
!rm master.zip
!cp -r ember-master/* .
!rm -r ember-master

--2020-04-05 14:44:29--  https://github.com/endgameinc/ember/archive/master.zip
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/endgameinc/ember/zip/master [following]
--2020-04-05 14:44:29--  https://codeload.github.com/endgameinc/ember/zip/master
Resolving codeload.github.com (codeload.github.com)... 140.82.114.9
Connecting to codeload.github.com (codeload.github.com)|140.82.114.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master.zip’

master.zip              [  <=>               ]  11.22M  13.8MB/s    in 0.8s    

2020-04-05 14:44:30 (13.8 MB/s) - ‘master.zip’ saved [11769023]

Archive:  master.zip
04c37efb20ebeb7b99d8ec1d5cdd20ab0328bb36
   creating: ember-master/
  inflating: ember-master/LICENSE.txt  
  inflating: ember-master/README.md  
   creating:

In [0]:
!pip install -r requirements.txt
!python setup.py install

  Created wheel for lief: filename=lief-0.9.0-cp36-cp36m-linux_x86_64.whl size=3610316 sha256=63a57d72e6407f31638bbe7a16e410bc9f81a0191542d7228a8f43afd4c2b073
  Stored in directory: /root/.cache/pip/wheels/7f/7d/da/deca5cc6d3c5f0d2612e55c691b7c2e57087df18de92733bff
Successfully built lief
running install
running bdist_egg
running egg_info
creating ember.egg-info
writing ember.egg-info/PKG-INFO
writing dependency_links to ember.egg-info/dependency_links.txt
writing requirements to ember.egg-info/requires.txt
writing top-level names to ember.egg-info/top_level.txt
writing manifest file 'ember.egg-info/SOURCES.txt'
reading manifest file 'ember.egg-info/SOURCES.txt'
writing manifest file 'ember.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/ember
copying ember/__init__.py -> build/lib/ember
copying ember/features.py -> build/lib/ember
creating build/bdist.linux-x86_64
cr

In [0]:
import ember
ember.create_vectorized_features("ember_2017_2/")
ember.create_metadata("ember_2017_2/")

Vectorizing training set


100%|██████████| 900000/900000 [12:23<00:00, 1211.16it/s]


Vectorizing test set


100%|██████████| 200000/200000 [02:45<00:00, 1209.59it/s]


sha256  ... label
0        0abb4fda7d5b13801d63bee53e5e256be43e141faa077a...  ...     0
1        d4206650743b3d519106dea10a38a55c30467c3d9f7875...  ...     0
2        c9cafff8a596ba8a80bafb4ba8ae6f2ef3329d95b85f15...  ...     0
3        7f513818bcc276c531af2e641c597744da807e21cc1160...  ...     0
4        ca65e1c387a4cc9e7d8a8ce12bf1bcf9f534c9032b9d95...  ...     0
...                                                    ...  ...   ...
1099995  fffe314f23cee3a68ccab272934877d3bc18ec3bd905df...  ...     0
1099996  fffe7a1b23e04facc9ca91a93ac4a34e8b3040e023dbde...  ...     1
1099997  fffe801f51e7ec931515aa49a3d157a9c0fbcdca8c9d80...  ...     0
1099998  fffe92f9593649c4a7050302368189de45e2c1c06b04ea...  ...     1
1099999  ffffb259a4c5e25ae1437af59caafb718cf8879187cc8c...  ...     1

[1100000 rows x 4 columns]

In [0]:
#!cp ember_2017_2/X_train.dat drive/My\ Drive/data/ember_2017_2/
#!cp ember_2017_2/y_train.dat drive/My\ Drive/data/ember_2017_2/
!cp ember_2017_2/X_test.dat drive/My\ Drive/data/ember_2017_2/
!cp ember_2017_2/y_test.dat drive/My\ Drive/data/ember_2017_2/
!cp ember_2017_2/metadata.csv drive/My\ Drive/data/ember_2017_2/

# Packages

In [0]:
#NEED MORE RAMMM
a = []
while(1):
    a.append("1")

# Model Structure

In [0]:
def make_model():
  import tensorflow as tf
  from tensorflow import keras
  from tensorflow.keras import layers
  feature_size=2381
  tf.compat.v1.disable_eager_execution()

  keras.backend.clear_session()
  
  #Model architecture
  from tensorflow.keras import layers
  
  model = tf.keras.Sequential()
  model.add(layers.InputLayer(input_shape=(1,feature_size)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Dense(1500, activation='relu'))
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(1, activation='sigmoid'))

  model.compile(tf.keras.optimizers.Adam(learning_rate=0.001),
            loss='binary_crossentropy',
            metrics=['accuracy',tf.keras.metrics.AUC(),tf.keras.metrics.Precision()])
  print(model.summary())
  return model

In [0]:
model = make_model()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dropout (Dropout)            (None, 1, 2381)           0         
_________________________________________________________________
dense (Dense)                (None, 1, 1500)           3573000   
_________________________________________________________________
dropout_1 (Dropout)          (None, 1, 1500)           0         
_________________________________________________________________
dense_1 (Dense)              (None, 1, 1)              1501      
Total params: 3,574,501
Trainable params: 3,574,501
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.save("drive/My Drive/data/pickles/"+'my_model.h5')

# Standardizing Data and Taking Relevent Samples

Since the library lief has done the heavy lifting in terms of vectorizing the features, actually--  I spent like 6+ hours doing that myself to come to figure out I didn't need to do it... We must normalize the data values. Since the data is too large to load into memory and fit to the scaler in the same runtime execution, we can prep the data in steps.

In [0]:
import ember
X_train, y_train, X_test, y_test = ember.read_vectorized_features("ember_2017_2/")
metadata_dataframe = ember.read_metadata("ember_2017_2/")

In [0]:
labelrows = (y_train != -1)

In [0]:
X_train = X_train[labelrows]
y_train = y_train[labelrows]

In [0]:
#run this to make a h5 file in the session in case the ram crashes
import h5py
h5f = h5py.File('X_train.h5', 'w')
h5f.create_dataset('X_train', data=X_train)
h5f.close()

In [0]:
import h5py
h5f = h5py.File('y_train.h5', 'w')
h5f.create_dataset('y_train', data=y_train)
h5f.close()

In [0]:
#read to avoid having to filter the data for labeled samples again
import h5py
h5f = h5py.File('X_train.h5','r')
X_train = h5f['X_train'][:]
h5f.close()

In [0]:
#by checking the size of y_train, we find that there's 600k labels. Cool, we can partial fit the standardScaler to avoid overloading the memory
from sklearn.preprocessing import StandardScaler
mms = StandardScaler()

for x in range(0,600000,100000):
  mms.partial_fit(X_train[x:x+100000])

In [0]:
#do this in case the ram crashes...
with open("mms_scaler","wb") as f:
  import pickle
  pickle.dump(mms,f)
  f.close()

In [0]:
#transform the data
X_train = mms.transform(X_train)

In [0]:
#reshape data to have 3 channels...
import numpy as np
X_train = np.reshape(X_train,(-1,1,2381))
y_train = np.reshape(y_train,(-1,1,1))

# Model Training

Training is done in a separate notebook namely because there was lots of testing hyperparameters. However, here is the execution code minus any outputs. The block of code was executed separately several times with 1 epoch set to have saved models in case it overshoot the minimum.

In [0]:
%tensorflow_version 2.x
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

pkl_base="drive/My Drive/data/pickles/"

model.compile(tf.keras.optimizers.Adam(learning_rate=0.01),
          loss='binary_crossentropy',
          metrics=['accuracy',tf.keras.metrics.AUC(),tf.keras.metrics.Precision()])

history = model.fit(X_train, y_train,
                batch_size=256,
                epochs=1,
                  validation_data =((X_train[600000-120000:600000],y_train[600000-120000:600000]))
                  )
model_name="my_model2.h5"
model_weights="weights2.h5"
model.save(pkl_base+model_name)
model.save_weights(pkl_base+model_weights)
print(model_name,model_weights," are saved.")

# Model Testing

In [0]:
#read to avoid having to filter the data for labeled samples again
import h5py
h5f = h5py.File('drive/My Drive/data/ember_2017_2/X_test.h5','r')
X_test = h5f['X_test'][:]
h5f.close()
#read to avoid having to filter the data for labeled samples again
import h5py
h5f = h5py.File('drive/My Drive/data/ember_2017_2/y_test.h5','r')
y_test = h5f['y_test'][:]
h5f.close()

In [0]:
#converting testing data too
from sklearn.preprocessing import StandardScaler
mms = StandardScaler()

X_test = mms.fit_transform(X_test)

In [0]:
import numpy as np
X_test = np.reshape(X_test,(-1,1,2381))
y_test = np.reshape(y_test,(-1,1,1))

In [0]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
model = tf.keras.models.load_model("drive/My Drive/data/pickles/"+'my_model_test-tpu3.h5')

model.compile(tf.keras.optimizers.Adam(learning_rate=0.01),
          loss='binary_crossentropy',
          metrics=['accuracy',tf.keras.metrics.AUC(),tf.keras.metrics.Precision()])

results =model.evaluate(X_test,y_test)
print("loss: %gl,acc: %gl"%(results[0],results[1]))

loss: 5.09298l,acc: 0.97538l


In [0]:
pred = model.predict(X_test)

In [0]:
y_test = np.reshape(y_test,(-1))
pred = np.reshape(pred,(-1))

In [0]:
y_test,pred

(array([1., 1., 0., ..., 0., 1., 1.], dtype=float32),
 array([1., 1., 0., ..., 0., 1., 1.], dtype=float32))

In [0]:
y_test.shape,pred.shape

((200000,), (200000,))

In [0]:
from sklearn import metrics
fpr, tpr, tresh = metrics.roc_curve(y_test,pred)

In [0]:
metrics.auc(fpr,tpr)

0.9853060999000001

In [0]:
y_test_int = np.asarray(y_test,dtype=int)
pred_int=np.asarray(pred,dtype=int)

In [0]:
from sklearn.metrics import f1_score

fscore = f1_score(y_test_int, pred_int) 
fscore

0.9724353081247269

In [0]:
import sklearn

In [63]:
precision = sklearn.metrics.precision_score(y_test_int,pred_int)
precision

0.9770540788822822

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_int,pred_int,labels=[0,1])

In [0]:
import pandas as pd
pd.DataFrame(cm,columns=['pred_benign','pred_malicious'],index=['is_benign','is_malicious'])

pred_benign  pred_malicious
is_benign           97727            2273
is_malicious         3214           96786

In [0]:
!wget https://the.earth.li/~sgtatham/putty/latest/w32/putty.exe

--2020-04-05 14:50:44--  https://the.earth.li/~sgtatham/putty/latest/w32/putty.exe
Resolving the.earth.li (the.earth.li)... 93.93.131.124, 2a00:1098:86:4d:c0ff:ee:15:900d
Connecting to the.earth.li (the.earth.li)|93.93.131.124|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://the.earth.li/~sgtatham/putty/0.73/w32/putty.exe [following]
--2020-04-05 14:50:45--  https://the.earth.li/~sgtatham/putty/0.73/w32/putty.exe
Reusing existing connection to the.earth.li:443.
HTTP request sent, awaiting response... 200 OK
Length: 1096080 (1.0M) [application/x-msdos-program]
Saving to: ‘putty.exe’

putty.exe           100%[===================>]   1.04M  1.27MB/s    in 0.8s    

2020-04-05 14:50:46 (1.27 MB/s) - ‘putty.exe’ saved [1096080/1096080]



In [0]:
!cp drive/My\ Drive/data/pickles/mms_scaler_test .

In [0]:
!cp drive/My\ Drive/data/pickles/my_model_test-tpu3.h5 model.h5

In [0]:
def test_pefile(pefile):
  try:
    import ember
  except:
    !wget https://github.com/endgameinc/ember/archive/master.zip
    !unzip master.zip
    !rm master.zip
    !cp -r ember-master/* .
    !rm -r ember-master
    !pip install -r requirements.txt
    !python setup.py install
    import ember

  from sklearn.preprocessing import StandardScaler
  import tensorflow as tf
  tf.compat.v1.disable_eager_execution()

  with open("mms_scaler_test","rb") as f:
    import pickle
    mms = pickle.load(f)
    f.close()
  
  sample_data = open(pefile, "rb").read()
  extractor = ember.PEFeatureExtractor(2)
  sample_data = np.array(extractor.feature_vector(sample_data), dtype=np.float32)
  sample_data = mms.transform([sample_data])
  sample_data = np.reshape(sample_data,(-1,1,2381))

  model = tf.keras.models.load_model('model.h5')
  pred = model.predict_classes(sample_data)

  return pred

In [0]:
test_pefile("putty.exe")

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[[0]]], dtype=int32)